language: ruby
rvm:
- 2.1.1
env:
  matrix:
  - INTEGRATION=true
  - INTEGRATION=false
  global:
  - secure: goGCFuLSsyB5hJgxfkN0C+QSMmhFypjggfIxN+j+RtZd5sxyV5T2Kyz5o1vQ+iLkigKO+rMsGtLdQ9CC4guReUt/YnxsodNiEGyx3+jexG9t6qYX8xfNmxDuAu7RB+y3HNzaNAh7A46sxZNducBYxiwOuH99Fvl8Q42Lj+QKNZs=
  - secure: DiPfXlgyaUI/BtPCcEy7Zu/vaHqT7p0NIlaJVD3jSlBN4wndP6dgFuzA7WtEMRnn5E60sjP6Jy4gPU7T54Lyil1BNbSiLF/CFaYkRumNIONhLzuiPezb4s4BFg1zta1l0d3TKkeu+6UyTaaTz4yBkCVvGNwzq4pHyH2zFg6BuYw=
  - secure: CTU1UZ8zGiZ/zlNYtjm4qddmxcU/jRssg0Mrak6zUl/XKxVEzBqffsKwkPhjlrD8AInPHPdD4uROxRIFlhFaji8ULvvAaFYsO8ljBTI4aI59fK/EMWy/7ZfitkOlGPFHVSZErP8KyyLyWa5Rd2fcml0itF6SeAfU/EUjOOO9AcU=
install:
- cd backend
- ssh-keyscan -t rsa,dsa github.com,192.30.252.129 >> ~/.ssh/known_hosts
- bundle install
script:
- bundle exec rake
